[build]
  publish = "dist"
  command = "npm run build"
  environment = { VITE_API_BASE_URL = "https://canvasconnect-production.up.railway.app", VITE_SOCKET_URL = "https://canvasconnect-production.up.railway.app" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
