[build]
  publish = "dist"
  command = "npm run build"
  environment = { VITE_API_BASE_URL = "https://canvasconnect-fcch.onrender.com", VITE_SOCKET_URL = "https://canvasconnect-fcch.onrender.com" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
