[build]
builder = "nixpacks"

[deploy]
startCommand = "python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
watchPaths = ["**/*.py", "requirements.txt", "Procfile"]
