[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"

[env]
PORT = { default = "5000" }
NIXPACKS_PYTHON_VERSION = "3.9"
FLASK_ENV = "production"
